2023-11-18 19:20:11,450 - INFO - Accepted connection from ('127.0.0.1', 63929)
2023-11-18 19:20:11,457 - INFO - Handshake was successful!
2023-11-18 19:20:11,653 - INFO - Received successfully Master Key and IV.
2023-11-18 19:20:11,736 - INFO - Received the encrypted data
2023-11-18 19:20:11,917 - INFO - Trace was stored successfully
2023-11-18 19:20:25,596 - INFO - Accepted connection from ('127.0.0.1', 63956)
2023-11-18 19:20:25,606 - INFO - Handshake was successful!
2023-11-18 19:20:25,646 - INFO - Received successfully Master Key and IV.
2023-11-18 19:20:25,806 - INFO - Received the encrypted data
2023-11-18 19:20:25,918 - INFO - Trace was stored successfully
2023-11-18 19:20:27,085 - INFO - Accepted connection from ('127.0.0.1', 63963)
2023-11-18 19:20:27,090 - INFO - Handshake was successful!
2023-11-18 19:20:27,137 - INFO - Received successfully Master Key and IV.
2023-11-18 19:20:27,287 - INFO - Received the encrypted data
2023-11-18 19:20:27,397 - INFO - Trace was stored successfully
2023-11-18 19:20:50,376 - INFO - Accepted connection from ('127.0.0.1', 64008)
2023-11-18 19:20:50,380 - INFO - Handshake was successful!
2023-11-18 19:20:50,423 - INFO - Received successfully Master Key and IV.
2023-11-18 19:20:50,577 - INFO - Received the encrypted data
2023-11-18 19:20:50,697 - INFO - Trace was stored successfully
2023-11-18 19:20:53,421 - INFO - Accepted connection from ('127.0.0.1', 64019)
2023-11-18 19:20:53,426 - INFO - Handshake was successful!
2023-11-18 19:20:53,474 - INFO - Received successfully Master Key and IV.
2023-11-18 19:20:53,650 - INFO - Received the encrypted data
2023-11-18 19:20:53,771 - INFO - Trace was stored successfully
2023-11-18 19:20:54,506 - INFO - Accepted connection from ('127.0.0.1', 64028)
2023-11-18 19:20:54,506 - INFO - Handshake was successful!
2023-11-18 19:20:54,556 - INFO - Received successfully Master Key and IV.
2023-11-18 19:20:54,707 - INFO - Received the encrypted data
2023-11-18 19:20:54,843 - INFO - Trace was stored successfully
2023-11-18 19:21:16,136 - INFO - Accepted connection from ('127.0.0.1', 64049)
2023-11-18 19:21:16,141 - INFO - Handshake was successful!
2023-11-18 19:21:16,175 - INFO - Received successfully Master Key and IV.
2023-11-18 19:21:16,347 - INFO - Received the encrypted data
2023-11-18 19:21:16,460 - INFO - Trace was stored successfully
2023-11-18 19:21:17,162 - INFO - Accepted connection from ('127.0.0.1', 64057)
2023-11-18 19:21:17,166 - INFO - Handshake was successful!
2023-11-18 19:21:17,214 - INFO - Received successfully Master Key and IV.
2023-11-18 19:21:17,370 - INFO - Received the encrypted data
2023-11-18 19:21:17,477 - INFO - Trace was stored successfully
2023-11-18 19:21:18,296 - INFO - Accepted connection from ('127.0.0.1', 64064)
2023-11-18 19:21:18,300 - INFO - Handshake was successful!
2023-11-18 19:21:18,336 - INFO - Received successfully Master Key and IV.
2023-11-18 19:21:18,500 - INFO - Received the encrypted data
2023-11-18 19:21:18,607 - INFO - Trace was stored successfully
2023-11-18 19:21:19,347 - INFO - Accepted connection from ('127.0.0.1', 64070)
2023-11-18 19:21:19,347 - INFO - Handshake was successful!
2023-11-18 19:21:19,399 - INFO - Received successfully Master Key and IV.
2023-11-18 19:21:19,555 - INFO - Received the encrypted data
2023-11-18 19:21:19,685 - INFO - Trace was stored successfully
2023-11-18 19:26:29,338 - INFO - Accepted connection from ('127.0.0.1', 64558)
2023-11-18 19:26:29,342 - INFO - Handshake was successful!
2023-11-18 19:26:29,415 - INFO - Received successfully Master Key and IV.
2023-11-18 19:26:29,416 - ERROR - TLS handshake error: (-1, 'Unexpected EOF')
Traceback (most recent call last):
  File "C:\Users\Marios Stefanidis\Documents\GitHub\Diploma-Thesis\code\seedlink-server\decryption\ssl_con.py", line 284, in handle_client
    encrypted_total_size = ssl_socket.recv(4096)
                           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marios Stefanidis\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenSSL\SSL.py", line 2076, in recv
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\Marios Stefanidis\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenSSL\SSL.py", line 1847, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')
2023-11-18 19:34:05,208 - INFO - Accepted connection from ('127.0.0.1', 65056)
2023-11-18 19:34:05,213 - INFO - Handshake was successful!
2023-11-18 19:34:05,283 - INFO - Received successfully Master Key and IV.
2023-11-18 19:34:05,283 - ERROR - TLS handshake error: (-1, 'Unexpected EOF')
Traceback (most recent call last):
  File "C:\Users\Marios Stefanidis\Documents\GitHub\Diploma-Thesis\code\seedlink-server\decryption\ssl_con.py", line 284, in handle_client
    encrypted_total_size = ssl_socket.recv(4096)
                           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marios Stefanidis\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenSSL\SSL.py", line 2076, in recv
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\Marios Stefanidis\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenSSL\SSL.py", line 1847, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')
2023-11-18 19:38:06,230 - INFO - Accepted connection from ('127.0.0.1', 65403)
2023-11-18 19:38:06,244 - INFO - Handshake was successful!
2023-11-18 19:38:06,327 - INFO - Received successfully Master Key and IV.
2023-11-18 19:38:06,327 - ERROR - TLS handshake error: (-1, 'Unexpected EOF')
Traceback (most recent call last):
  File "C:\Users\Marios Stefanidis\Documents\GitHub\Diploma-Thesis\code\seedlink-server\decryption\ssl_con.py", line 284, in handle_client
    encrypted_total_size = ssl_socket.recv(4096)
                           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marios Stefanidis\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenSSL\SSL.py", line 2076, in recv
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\Marios Stefanidis\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenSSL\SSL.py", line 1847, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')
2023-11-18 19:41:16,318 - INFO - Accepted connection from ('127.0.0.1', 49319)
2023-11-18 19:41:16,318 - INFO - Handshake was successful!
2023-11-18 19:41:16,382 - INFO - Received successfully Master Key and IV.
2023-11-18 19:41:16,527 - INFO - Received the encrypted data
2023-11-18 19:41:16,719 - INFO - Trace was stored successfully
2023-11-18 19:42:07,862 - INFO - Accepted connection from ('127.0.0.1', 49358)
2023-11-18 19:42:07,862 - INFO - Handshake was successful!
2023-11-18 19:42:07,908 - INFO - Received successfully Master Key and IV.
2023-11-18 19:42:08,083 - INFO - Received the encrypted data
2023-11-18 19:42:08,209 - INFO - Trace was stored successfully
2023-11-18 19:43:00,560 - INFO - Accepted connection from ('127.0.0.1', 49402)
2023-11-18 19:43:00,565 - INFO - Handshake was successful!
2023-11-18 19:43:00,608 - INFO - Received successfully Master Key and IV.
2023-11-18 19:43:00,773 - INFO - Received the encrypted data
2023-11-18 19:43:00,894 - INFO - Trace was stored successfully
2023-11-18 19:43:51,302 - INFO - Accepted connection from ('127.0.0.1', 49717)
2023-11-18 19:43:51,302 - INFO - Handshake was successful!
2023-11-18 19:43:51,351 - INFO - Received successfully Master Key and IV.
2023-11-18 19:43:51,656 - INFO - Received the encrypted data
2023-11-18 19:43:51,798 - INFO - Trace was stored successfully
2023-11-18 19:45:53,991 - INFO - Accepted connection from ('127.0.0.1', 49838)
2023-11-18 19:45:54,001 - INFO - Handshake was successful!
2023-11-18 19:45:54,050 - INFO - Received successfully Master Key and IV.
2023-11-18 19:45:54,272 - INFO - Received the encrypted data
2023-11-18 19:45:54,426 - INFO - Trace was stored successfully
2023-11-18 19:45:55,152 - INFO - Accepted connection from ('127.0.0.1', 49850)
2023-11-18 19:45:55,152 - INFO - Handshake was successful!
2023-11-18 19:45:55,199 - INFO - Received successfully Master Key and IV.
2023-11-18 19:45:55,399 - INFO - Received the encrypted data
2023-11-18 19:45:55,600 - INFO - Trace was stored successfully
2023-11-18 19:46:07,053 - INFO - Accepted connection from ('127.0.0.1', 49882)
2023-11-18 19:46:07,053 - INFO - Handshake was successful!
2023-11-18 19:46:07,109 - INFO - Received successfully Master Key and IV.
2023-11-18 19:46:07,318 - INFO - Received the encrypted data
2023-11-18 19:46:07,481 - INFO - Trace was stored successfully
2023-11-18 19:46:17,370 - INFO - Accepted connection from ('127.0.0.1', 49893)
2023-11-18 19:46:17,370 - INFO - Handshake was successful!
2023-11-18 19:46:17,430 - INFO - Received successfully Master Key and IV.
2023-11-18 19:46:17,589 - INFO - Received the encrypted data
2023-11-18 19:46:17,698 - INFO - Trace was stored successfully
